// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: api.proto

package protocol

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_UP    Direction = 1
	Direction_DOWN  Direction = 2
	Direction_LEFT  Direction = 3
	Direction_RIGHT Direction = 4
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		1: "UP",
		2: "DOWN",
		3: "LEFT",
		4: "RIGHT",
	}
	Direction_value = map[string]int32{
		"UP":    1,
		"DOWN":  2,
		"LEFT":  3,
		"RIGHT": 4,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Direction) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Direction(num)
	return nil
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

type APIResponse_GameStateMsg_Role int32

const (
	APIResponse_GameStateMsg_NORMAL APIResponse_GameStateMsg_Role = 0
	APIResponse_GameStateMsg_MASTER APIResponse_GameStateMsg_Role = 1
	APIResponse_GameStateMsg_DEPUTY APIResponse_GameStateMsg_Role = 2
	APIResponse_GameStateMsg_VIEWER APIResponse_GameStateMsg_Role = 3
)

// Enum value maps for APIResponse_GameStateMsg_Role.
var (
	APIResponse_GameStateMsg_Role_name = map[int32]string{
		0: "NORMAL",
		1: "MASTER",
		2: "DEPUTY",
		3: "VIEWER",
	}
	APIResponse_GameStateMsg_Role_value = map[string]int32{
		"NORMAL": 0,
		"MASTER": 1,
		"DEPUTY": 2,
		"VIEWER": 3,
	}
)

func (x APIResponse_GameStateMsg_Role) Enum() *APIResponse_GameStateMsg_Role {
	p := new(APIResponse_GameStateMsg_Role)
	*p = x
	return p
}

func (x APIResponse_GameStateMsg_Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (APIResponse_GameStateMsg_Role) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[1].Descriptor()
}

func (APIResponse_GameStateMsg_Role) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[1]
}

func (x APIResponse_GameStateMsg_Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *APIResponse_GameStateMsg_Role) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = APIResponse_GameStateMsg_Role(num)
	return nil
}

// Deprecated: Use APIResponse_GameStateMsg_Role.Descriptor instead.
func (APIResponse_GameStateMsg_Role) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1, 4, 0}
}

type APIRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*APIRequest_Connect
	//	*APIRequest_Ping
	//	*APIRequest_CreateGame
	//	*APIRequest_DiscoverGames
	//	*APIRequest_JoinGame
	//	*APIRequest_SteerSnake
	//	*APIRequest_GetGameState
	//	*APIRequest_ExitGame
	//	*APIRequest_Disconnect
	Type isAPIRequest_Type `protobuf_oneof:"Type"`
}

func (x *APIRequest) Reset() {
	*x = APIRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRequest) ProtoMessage() {}

func (x *APIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRequest.ProtoReflect.Descriptor instead.
func (*APIRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (m *APIRequest) GetType() isAPIRequest_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *APIRequest) GetConnect() *APIRequest_ConnectMsg {
	if x, ok := x.GetType().(*APIRequest_Connect); ok {
		return x.Connect
	}
	return nil
}

func (x *APIRequest) GetPing() *APIRequest_PingMsg {
	if x, ok := x.GetType().(*APIRequest_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *APIRequest) GetCreateGame() *APIRequest_CreateGameMsg {
	if x, ok := x.GetType().(*APIRequest_CreateGame); ok {
		return x.CreateGame
	}
	return nil
}

func (x *APIRequest) GetDiscoverGames() *APIRequest_DiscoverGamesMsg {
	if x, ok := x.GetType().(*APIRequest_DiscoverGames); ok {
		return x.DiscoverGames
	}
	return nil
}

func (x *APIRequest) GetJoinGame() *APIRequest_JoinGameMsg {
	if x, ok := x.GetType().(*APIRequest_JoinGame); ok {
		return x.JoinGame
	}
	return nil
}

func (x *APIRequest) GetSteerSnake() *APIRequest_SteerSnakeMsg {
	if x, ok := x.GetType().(*APIRequest_SteerSnake); ok {
		return x.SteerSnake
	}
	return nil
}

func (x *APIRequest) GetGetGameState() *APIRequest_GetGameStateMsg {
	if x, ok := x.GetType().(*APIRequest_GetGameState); ok {
		return x.GetGameState
	}
	return nil
}

func (x *APIRequest) GetExitGame() *APIRequest_ExitGameMsg {
	if x, ok := x.GetType().(*APIRequest_ExitGame); ok {
		return x.ExitGame
	}
	return nil
}

func (x *APIRequest) GetDisconnect() *APIRequest_DisconnectMsg {
	if x, ok := x.GetType().(*APIRequest_Disconnect); ok {
		return x.Disconnect
	}
	return nil
}

type isAPIRequest_Type interface {
	isAPIRequest_Type()
}

type APIRequest_Connect struct {
	Connect *APIRequest_ConnectMsg `protobuf:"bytes,1,opt,name=connect,oneof"`
}

type APIRequest_Ping struct {
	Ping *APIRequest_PingMsg `protobuf:"bytes,2,opt,name=ping,oneof"`
}

type APIRequest_CreateGame struct {
	CreateGame *APIRequest_CreateGameMsg `protobuf:"bytes,3,opt,name=create_game,json=createGame,oneof"`
}

type APIRequest_DiscoverGames struct {
	DiscoverGames *APIRequest_DiscoverGamesMsg `protobuf:"bytes,4,opt,name=discover_games,json=discoverGames,oneof"`
}

type APIRequest_JoinGame struct {
	JoinGame *APIRequest_JoinGameMsg `protobuf:"bytes,5,opt,name=join_game,json=joinGame,oneof"`
}

type APIRequest_SteerSnake struct {
	SteerSnake *APIRequest_SteerSnakeMsg `protobuf:"bytes,6,opt,name=steer_snake,json=steerSnake,oneof"`
}

type APIRequest_GetGameState struct {
	GetGameState *APIRequest_GetGameStateMsg `protobuf:"bytes,7,opt,name=get_game_state,json=getGameState,oneof"`
}

type APIRequest_ExitGame struct {
	ExitGame *APIRequest_ExitGameMsg `protobuf:"bytes,8,opt,name=exit_game,json=exitGame,oneof"`
}

type APIRequest_Disconnect struct {
	Disconnect *APIRequest_DisconnectMsg `protobuf:"bytes,9,opt,name=disconnect,oneof"`
}

func (*APIRequest_Connect) isAPIRequest_Type() {}

func (*APIRequest_Ping) isAPIRequest_Type() {}

func (*APIRequest_CreateGame) isAPIRequest_Type() {}

func (*APIRequest_DiscoverGames) isAPIRequest_Type() {}

func (*APIRequest_JoinGame) isAPIRequest_Type() {}

func (*APIRequest_SteerSnake) isAPIRequest_Type() {}

func (*APIRequest_GetGameState) isAPIRequest_Type() {}

func (*APIRequest_ExitGame) isAPIRequest_Type() {}

func (*APIRequest_Disconnect) isAPIRequest_Type() {}

type APIResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//	*APIResponse_SuccessConnect
	//	*APIResponse_Ack
	//	*APIResponse_Error
	//	*APIResponse_GameList
	//	*APIResponse_GameState
	Type isAPIResponse_Type `protobuf_oneof:"Type"`
}

func (x *APIResponse) Reset() {
	*x = APIResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResponse) ProtoMessage() {}

func (x *APIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResponse.ProtoReflect.Descriptor instead.
func (*APIResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (m *APIResponse) GetType() isAPIResponse_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *APIResponse) GetSuccessConnect() *APIResponse_SuccessConnectMsg {
	if x, ok := x.GetType().(*APIResponse_SuccessConnect); ok {
		return x.SuccessConnect
	}
	return nil
}

func (x *APIResponse) GetAck() *APIResponse_AckMsg {
	if x, ok := x.GetType().(*APIResponse_Ack); ok {
		return x.Ack
	}
	return nil
}

func (x *APIResponse) GetError() *APIResponse_ErrorMsg {
	if x, ok := x.GetType().(*APIResponse_Error); ok {
		return x.Error
	}
	return nil
}

func (x *APIResponse) GetGameList() *APIResponse_GameListMsg {
	if x, ok := x.GetType().(*APIResponse_GameList); ok {
		return x.GameList
	}
	return nil
}

func (x *APIResponse) GetGameState() *APIResponse_GameStateMsg {
	if x, ok := x.GetType().(*APIResponse_GameState); ok {
		return x.GameState
	}
	return nil
}

type isAPIResponse_Type interface {
	isAPIResponse_Type()
}

type APIResponse_SuccessConnect struct {
	SuccessConnect *APIResponse_SuccessConnectMsg `protobuf:"bytes,1,opt,name=successConnect,oneof"`
}

type APIResponse_Ack struct {
	Ack *APIResponse_AckMsg `protobuf:"bytes,2,opt,name=ack,oneof"`
}

type APIResponse_Error struct {
	Error *APIResponse_ErrorMsg `protobuf:"bytes,3,opt,name=error,oneof"`
}

type APIResponse_GameList struct {
	GameList *APIResponse_GameListMsg `protobuf:"bytes,4,opt,name=game_list,json=gameList,oneof"`
}

type APIResponse_GameState struct {
	GameState *APIResponse_GameStateMsg `protobuf:"bytes,5,opt,name=game_state,json=gameState,oneof"`
}

func (*APIResponse_SuccessConnect) isAPIResponse_Type() {}

func (*APIResponse_Ack) isAPIResponse_Type() {}

func (*APIResponse_Error) isAPIResponse_Type() {}

func (*APIResponse_GameList) isAPIResponse_Type() {}

func (*APIResponse_GameState) isAPIResponse_Type() {}

type APIRequest_ConnectMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *APIRequest_ConnectMsg) Reset() {
	*x = APIRequest_ConnectMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIRequest_ConnectMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRequest_ConnectMsg) ProtoMessage() {}

func (x *APIRequest_ConnectMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRequest_ConnectMsg.ProtoReflect.Descriptor instead.
func (*APIRequest_ConnectMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0, 0}
}

type APIRequest_PingMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token *string `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
}

func (x *APIRequest_PingMsg) Reset() {
	*x = APIRequest_PingMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIRequest_PingMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRequest_PingMsg) ProtoMessage() {}

func (x *APIRequest_PingMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRequest_PingMsg.ProtoReflect.Descriptor instead.
func (*APIRequest_PingMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0, 1}
}

func (x *APIRequest_PingMsg) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

type APIRequest_CreateGameMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token        *string `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
	PlayerName   *string `protobuf:"bytes,2,req,name=player_name,json=playerName" json:"player_name,omitempty"`
	GameName     *string `protobuf:"bytes,3,req,name=game_name,json=gameName" json:"game_name,omitempty"`
	Width        *int32  `protobuf:"varint,4,req,name=width" json:"width,omitempty"`
	Height       *int32  `protobuf:"varint,5,req,name=height" json:"height,omitempty"`
	FoodStatic   *int32  `protobuf:"varint,6,req,name=food_static,json=foodStatic" json:"food_static,omitempty"`
	StateDelayMs *int32  `protobuf:"varint,7,req,name=state_delay_ms,json=stateDelayMs" json:"state_delay_ms,omitempty"`
}

func (x *APIRequest_CreateGameMsg) Reset() {
	*x = APIRequest_CreateGameMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIRequest_CreateGameMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRequest_CreateGameMsg) ProtoMessage() {}

func (x *APIRequest_CreateGameMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRequest_CreateGameMsg.ProtoReflect.Descriptor instead.
func (*APIRequest_CreateGameMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0, 2}
}

func (x *APIRequest_CreateGameMsg) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *APIRequest_CreateGameMsg) GetPlayerName() string {
	if x != nil && x.PlayerName != nil {
		return *x.PlayerName
	}
	return ""
}

func (x *APIRequest_CreateGameMsg) GetGameName() string {
	if x != nil && x.GameName != nil {
		return *x.GameName
	}
	return ""
}

func (x *APIRequest_CreateGameMsg) GetWidth() int32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *APIRequest_CreateGameMsg) GetHeight() int32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *APIRequest_CreateGameMsg) GetFoodStatic() int32 {
	if x != nil && x.FoodStatic != nil {
		return *x.FoodStatic
	}
	return 0
}

func (x *APIRequest_CreateGameMsg) GetStateDelayMs() int32 {
	if x != nil && x.StateDelayMs != nil {
		return *x.StateDelayMs
	}
	return 0
}

type APIRequest_DiscoverGamesMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token *string `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
}

func (x *APIRequest_DiscoverGamesMsg) Reset() {
	*x = APIRequest_DiscoverGamesMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIRequest_DiscoverGamesMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRequest_DiscoverGamesMsg) ProtoMessage() {}

func (x *APIRequest_DiscoverGamesMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRequest_DiscoverGamesMsg.ProtoReflect.Descriptor instead.
func (*APIRequest_DiscoverGamesMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0, 3}
}

func (x *APIRequest_DiscoverGamesMsg) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

type APIRequest_JoinGameMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token      *string `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
	PlayerName *string `protobuf:"bytes,2,req,name=player_name,json=playerName" json:"player_name,omitempty"`
	GameName   *string `protobuf:"bytes,3,req,name=game_name,json=gameName" json:"game_name,omitempty"`
	IsPlayer   *bool   `protobuf:"varint,4,req,name=is_player,json=isPlayer" json:"is_player,omitempty"`
}

func (x *APIRequest_JoinGameMsg) Reset() {
	*x = APIRequest_JoinGameMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIRequest_JoinGameMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRequest_JoinGameMsg) ProtoMessage() {}

func (x *APIRequest_JoinGameMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRequest_JoinGameMsg.ProtoReflect.Descriptor instead.
func (*APIRequest_JoinGameMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0, 4}
}

func (x *APIRequest_JoinGameMsg) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *APIRequest_JoinGameMsg) GetPlayerName() string {
	if x != nil && x.PlayerName != nil {
		return *x.PlayerName
	}
	return ""
}

func (x *APIRequest_JoinGameMsg) GetGameName() string {
	if x != nil && x.GameName != nil {
		return *x.GameName
	}
	return ""
}

func (x *APIRequest_JoinGameMsg) GetIsPlayer() bool {
	if x != nil && x.IsPlayer != nil {
		return *x.IsPlayer
	}
	return false
}

type APIRequest_SteerSnakeMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token     *string    `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
	Direction *Direction `protobuf:"varint,2,req,name=direction,enum=api.Direction" json:"direction,omitempty"`
}

func (x *APIRequest_SteerSnakeMsg) Reset() {
	*x = APIRequest_SteerSnakeMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIRequest_SteerSnakeMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRequest_SteerSnakeMsg) ProtoMessage() {}

func (x *APIRequest_SteerSnakeMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRequest_SteerSnakeMsg.ProtoReflect.Descriptor instead.
func (*APIRequest_SteerSnakeMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0, 5}
}

func (x *APIRequest_SteerSnakeMsg) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *APIRequest_SteerSnakeMsg) GetDirection() Direction {
	if x != nil && x.Direction != nil {
		return *x.Direction
	}
	return Direction_UP
}

type APIRequest_GetGameStateMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token *string `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
}

func (x *APIRequest_GetGameStateMsg) Reset() {
	*x = APIRequest_GetGameStateMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIRequest_GetGameStateMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRequest_GetGameStateMsg) ProtoMessage() {}

func (x *APIRequest_GetGameStateMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRequest_GetGameStateMsg.ProtoReflect.Descriptor instead.
func (*APIRequest_GetGameStateMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0, 6}
}

func (x *APIRequest_GetGameStateMsg) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

type APIRequest_ExitGameMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token *string `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
}

func (x *APIRequest_ExitGameMsg) Reset() {
	*x = APIRequest_ExitGameMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIRequest_ExitGameMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRequest_ExitGameMsg) ProtoMessage() {}

func (x *APIRequest_ExitGameMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRequest_ExitGameMsg.ProtoReflect.Descriptor instead.
func (*APIRequest_ExitGameMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0, 7}
}

func (x *APIRequest_ExitGameMsg) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

type APIRequest_DisconnectMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token *string `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
}

func (x *APIRequest_DisconnectMsg) Reset() {
	*x = APIRequest_DisconnectMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIRequest_DisconnectMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRequest_DisconnectMsg) ProtoMessage() {}

func (x *APIRequest_DisconnectMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRequest_DisconnectMsg.ProtoReflect.Descriptor instead.
func (*APIRequest_DisconnectMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0, 8}
}

func (x *APIRequest_DisconnectMsg) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

type APIResponse_SuccessConnectMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token   *string `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
	Timeout *int32  `protobuf:"varint,2,req,name=timeout" json:"timeout,omitempty"`
}

func (x *APIResponse_SuccessConnectMsg) Reset() {
	*x = APIResponse_SuccessConnectMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIResponse_SuccessConnectMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResponse_SuccessConnectMsg) ProtoMessage() {}

func (x *APIResponse_SuccessConnectMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResponse_SuccessConnectMsg.ProtoReflect.Descriptor instead.
func (*APIResponse_SuccessConnectMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1, 0}
}

func (x *APIResponse_SuccessConnectMsg) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *APIResponse_SuccessConnectMsg) GetTimeout() int32 {
	if x != nil && x.Timeout != nil {
		return *x.Timeout
	}
	return 0
}

type APIResponse_AckMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *APIResponse_AckMsg) Reset() {
	*x = APIResponse_AckMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIResponse_AckMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResponse_AckMsg) ProtoMessage() {}

func (x *APIResponse_AckMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResponse_AckMsg.ProtoReflect.Descriptor instead.
func (*APIResponse_AckMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1, 1}
}

type APIResponse_ErrorMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorMessage *string `protobuf:"bytes,1,req,name=error_message,json=errorMessage" json:"error_message,omitempty"`
}

func (x *APIResponse_ErrorMsg) Reset() {
	*x = APIResponse_ErrorMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIResponse_ErrorMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResponse_ErrorMsg) ProtoMessage() {}

func (x *APIResponse_ErrorMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResponse_ErrorMsg.ProtoReflect.Descriptor instead.
func (*APIResponse_ErrorMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1, 2}
}

func (x *APIResponse_ErrorMsg) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

type APIResponse_GameListMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Games []*APIResponse_GameListMsg_GameInfo `protobuf:"bytes,1,rep,name=games" json:"games,omitempty"`
}

func (x *APIResponse_GameListMsg) Reset() {
	*x = APIResponse_GameListMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIResponse_GameListMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResponse_GameListMsg) ProtoMessage() {}

func (x *APIResponse_GameListMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResponse_GameListMsg.ProtoReflect.Descriptor instead.
func (*APIResponse_GameListMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1, 3}
}

func (x *APIResponse_GameListMsg) GetGames() []*APIResponse_GameListMsg_GameInfo {
	if x != nil {
		return x.Games
	}
	return nil
}

type APIResponse_GameStateMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Snakes  []*APIResponse_GameStateMsg_Snake  `protobuf:"bytes,2,rep,name=snakes" json:"snakes,omitempty"`
	Foods   []*APIResponse_GameStateMsg_Coord  `protobuf:"bytes,3,rep,name=foods" json:"foods,omitempty"`
	Players []*APIResponse_GameStateMsg_Player `protobuf:"bytes,4,rep,name=players" json:"players,omitempty"`
}

func (x *APIResponse_GameStateMsg) Reset() {
	*x = APIResponse_GameStateMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIResponse_GameStateMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResponse_GameStateMsg) ProtoMessage() {}

func (x *APIResponse_GameStateMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResponse_GameStateMsg.ProtoReflect.Descriptor instead.
func (*APIResponse_GameStateMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1, 4}
}

func (x *APIResponse_GameStateMsg) GetSnakes() []*APIResponse_GameStateMsg_Snake {
	if x != nil {
		return x.Snakes
	}
	return nil
}

func (x *APIResponse_GameStateMsg) GetFoods() []*APIResponse_GameStateMsg_Coord {
	if x != nil {
		return x.Foods
	}
	return nil
}

func (x *APIResponse_GameStateMsg) GetPlayers() []*APIResponse_GameStateMsg_Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type APIResponse_GameListMsg_GameInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameName   *string `protobuf:"bytes,1,req,name=gameName" json:"gameName,omitempty"`
	Width      *int32  `protobuf:"varint,2,req,name=width" json:"width,omitempty"`
	Height     *int32  `protobuf:"varint,3,req,name=height" json:"height,omitempty"`
	StateDelay *int32  `protobuf:"varint,4,req,name=stateDelay" json:"stateDelay,omitempty"`
}

func (x *APIResponse_GameListMsg_GameInfo) Reset() {
	*x = APIResponse_GameListMsg_GameInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIResponse_GameListMsg_GameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResponse_GameListMsg_GameInfo) ProtoMessage() {}

func (x *APIResponse_GameListMsg_GameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResponse_GameListMsg_GameInfo.ProtoReflect.Descriptor instead.
func (*APIResponse_GameListMsg_GameInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1, 3, 0}
}

func (x *APIResponse_GameListMsg_GameInfo) GetGameName() string {
	if x != nil && x.GameName != nil {
		return *x.GameName
	}
	return ""
}

func (x *APIResponse_GameListMsg_GameInfo) GetWidth() int32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *APIResponse_GameListMsg_GameInfo) GetHeight() int32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *APIResponse_GameListMsg_GameInfo) GetStateDelay() int32 {
	if x != nil && x.StateDelay != nil {
		return *x.StateDelay
	}
	return 0
}

type APIResponse_GameStateMsg_Coord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X *int32 `protobuf:"zigzag32,1,req,name=x" json:"x,omitempty"`
	Y *int32 `protobuf:"zigzag32,2,req,name=y" json:"y,omitempty"`
}

func (x *APIResponse_GameStateMsg_Coord) Reset() {
	*x = APIResponse_GameStateMsg_Coord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIResponse_GameStateMsg_Coord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResponse_GameStateMsg_Coord) ProtoMessage() {}

func (x *APIResponse_GameStateMsg_Coord) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResponse_GameStateMsg_Coord.ProtoReflect.Descriptor instead.
func (*APIResponse_GameStateMsg_Coord) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1, 4, 0}
}

func (x *APIResponse_GameStateMsg_Coord) GetX() int32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *APIResponse_GameStateMsg_Coord) GetY() int32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

type APIResponse_GameStateMsg_Snake struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId      *int32                            `protobuf:"varint,1,req,name=player_id,json=playerId" json:"player_id,omitempty"`
	Points        []*APIResponse_GameStateMsg_Coord `protobuf:"bytes,2,rep,name=points" json:"points,omitempty"`
	HeadDirection *Direction                        `protobuf:"varint,3,req,name=head_direction,json=headDirection,enum=api.Direction" json:"head_direction,omitempty"`
}

func (x *APIResponse_GameStateMsg_Snake) Reset() {
	*x = APIResponse_GameStateMsg_Snake{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIResponse_GameStateMsg_Snake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResponse_GameStateMsg_Snake) ProtoMessage() {}

func (x *APIResponse_GameStateMsg_Snake) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResponse_GameStateMsg_Snake.ProtoReflect.Descriptor instead.
func (*APIResponse_GameStateMsg_Snake) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1, 4, 1}
}

func (x *APIResponse_GameStateMsg_Snake) GetPlayerId() int32 {
	if x != nil && x.PlayerId != nil {
		return *x.PlayerId
	}
	return 0
}

func (x *APIResponse_GameStateMsg_Snake) GetPoints() []*APIResponse_GameStateMsg_Coord {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *APIResponse_GameStateMsg_Snake) GetHeadDirection() Direction {
	if x != nil && x.HeadDirection != nil {
		return *x.HeadDirection
	}
	return Direction_UP
}

type APIResponse_GameStateMsg_Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  *string                        `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Id    *int32                         `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Score *int32                         `protobuf:"varint,3,req,name=score" json:"score,omitempty"`
	Role  *APIResponse_GameStateMsg_Role `protobuf:"varint,4,req,name=role,enum=api.APIResponse_GameStateMsg_Role" json:"role,omitempty"`
}

func (x *APIResponse_GameStateMsg_Player) Reset() {
	*x = APIResponse_GameStateMsg_Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIResponse_GameStateMsg_Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResponse_GameStateMsg_Player) ProtoMessage() {}

func (x *APIResponse_GameStateMsg_Player) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResponse_GameStateMsg_Player.ProtoReflect.Descriptor instead.
func (*APIResponse_GameStateMsg_Player) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1, 4, 2}
}

func (x *APIResponse_GameStateMsg_Player) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *APIResponse_GameStateMsg_Player) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *APIResponse_GameStateMsg_Player) GetScore() int32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

func (x *APIResponse_GameStateMsg_Player) GetRole() APIResponse_GameStateMsg_Role {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return APIResponse_GameStateMsg_NORMAL
}

var File_api_proto protoreflect.FileDescriptor

var file_api_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69,
	0x22, 0xca, 0x09, 0x0a, 0x0a, 0x41, 0x50, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x36, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x50, 0x49, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x4d, 0x73, 0x67, 0x48, 0x00,
	0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x40, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x5f, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x49, 0x0a, 0x0e, 0x64, 0x69, 0x73, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x73, 0x4d,
	0x73, 0x67, 0x48, 0x00, 0x52, 0x0d, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x47, 0x61,
	0x6d, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x09, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x67, 0x61, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x50, 0x49,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65,
	0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x08, 0x6a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x12,
	0x40, 0x0a, 0x0b, 0x73, 0x74, 0x65, 0x65, 0x72, 0x5f, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x74, 0x65, 0x65, 0x72, 0x53, 0x6e, 0x61, 0x6b, 0x65,
	0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x74, 0x65, 0x65, 0x72, 0x53, 0x6e, 0x61, 0x6b,
	0x65, 0x12, 0x47, 0x0a, 0x0e, 0x67, 0x65, 0x74, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x41, 0x50, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x0c, 0x67, 0x65,
	0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x3a, 0x0a, 0x09, 0x65, 0x78,
	0x69, 0x74, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x45,
	0x78, 0x69, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x08, 0x65, 0x78,
	0x69, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x41, 0x50, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x69, 0x73, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x0a, 0x64, 0x69, 0x73,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x1a, 0x0c, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x4d, 0x73, 0x67, 0x1a, 0x1f, 0x0a, 0x07, 0x50, 0x69, 0x6e, 0x67, 0x4d, 0x73, 0x67,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0xd8, 0x01, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1f,
	0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x02, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64,
	0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x02,
	0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6f,
	0x6f, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x18, 0x06, 0x20, 0x02, 0x28, 0x05, 0x52,
	0x0a, 0x66, 0x6f, 0x6f, 0x64, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x12, 0x24, 0x0a, 0x0e, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x5f, 0x6d, 0x73, 0x18, 0x07, 0x20,
	0x02, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x4d,
	0x73, 0x1a, 0x28, 0x0a, 0x10, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x47, 0x61, 0x6d,
	0x65, 0x73, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x7e, 0x0a, 0x0b, 0x4a,
	0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x69, 0x73, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x04, 0x20, 0x02, 0x28,
	0x08, 0x52, 0x08, 0x69, 0x73, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x1a, 0x53, 0x0a, 0x0d, 0x53,
	0x74, 0x65, 0x65, 0x72, 0x53, 0x6e, 0x61, 0x6b, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x2c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x1a, 0x27, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x23, 0x0a, 0x0b, 0x45, 0x78, 0x69,
	0x74, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x25,
	0x0a, 0x0d, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4d, 0x73, 0x67, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x06, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0xc0, 0x09,
	0x0a, 0x0b, 0x41, 0x50, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a,
	0x0e, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x50, 0x49, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x0e, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x2b, 0x0a, 0x03, 0x61,
	0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41,
	0x50, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41, 0x63, 0x6b, 0x4d, 0x73,
	0x67, 0x48, 0x00, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x12, 0x31, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x50,
	0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d,
	0x73, 0x67, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x3b, 0x0a, 0x09, 0x67,
	0x61, 0x6d, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x08,
	0x67, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3e, 0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x09, 0x67,
	0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x43, 0x0a, 0x11, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x05, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x1a, 0x08, 0x0a,
	0x06, 0x41, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x1a, 0x2f, 0x0a, 0x08, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x73, 0x67, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0xc0, 0x01, 0x0a, 0x0b, 0x47, 0x61, 0x6d,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x3b, 0x0a, 0x05, 0x67, 0x61, 0x6d, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x50,
	0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05,
	0x67, 0x61, 0x6d, 0x65, 0x73, 0x1a, 0x74, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20,
	0x02, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x04, 0x20, 0x02, 0x28, 0x05, 0x52,
	0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x1a, 0xba, 0x04, 0x0a, 0x0c,
	0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x3b, 0x0a, 0x06,
	0x73, 0x6e, 0x61, 0x6b, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x2e, 0x53, 0x6e, 0x61, 0x6b,
	0x65, 0x52, 0x06, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x05, 0x66, 0x6f, 0x6f,
	0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41,
	0x50, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x52, 0x05, 0x66,
	0x6f, 0x6f, 0x64, 0x73, 0x12, 0x3e, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x50, 0x49, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x4d, 0x73, 0x67, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x73, 0x1a, 0x23, 0x0a, 0x05, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x12, 0x0c, 0x0a,
	0x01, 0x78, 0x18, 0x01, 0x20, 0x02, 0x28, 0x11, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x11, 0x52, 0x01, 0x79, 0x1a, 0x98, 0x01, 0x0a, 0x05, 0x53, 0x6e,
	0x61, 0x6b, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x3b, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x50, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x2e,
	0x43, 0x6f, 0x6f, 0x72, 0x64, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x35, 0x0a,
	0x0e, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x68, 0x65, 0x61, 0x64, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x7a, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28,
	0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x36, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65,
	0x18, 0x04, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x50, 0x49,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x4d, 0x73, 0x67, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65,
	0x22, 0x36, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x52, 0x4d,
	0x41, 0x4c, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x41, 0x53, 0x54, 0x45, 0x52, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x50, 0x55, 0x54, 0x59, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06,
	0x56, 0x49, 0x45, 0x57, 0x45, 0x52, 0x10, 0x03, 0x42, 0x06, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x2a, 0x32, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x06, 0x0a,
	0x02, 0x55, 0x50, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x02, 0x12,
	0x08, 0x0a, 0x04, 0x4c, 0x45, 0x46, 0x54, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x49, 0x47,
	0x48, 0x54, 0x10, 0x04, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x61, 0x70, 0x69,
}

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData = file_api_proto_rawDesc
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_rawDescData)
	})
	return file_api_proto_rawDescData
}

var file_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_proto_goTypes = []interface{}{
	(Direction)(0),                           // 0: api.Direction
	(APIResponse_GameStateMsg_Role)(0),       // 1: api.APIResponse.GameStateMsg.Role
	(*APIRequest)(nil),                       // 2: api.APIRequest
	(*APIResponse)(nil),                      // 3: api.APIResponse
	(*APIRequest_ConnectMsg)(nil),            // 4: api.APIRequest.ConnectMsg
	(*APIRequest_PingMsg)(nil),               // 5: api.APIRequest.PingMsg
	(*APIRequest_CreateGameMsg)(nil),         // 6: api.APIRequest.CreateGameMsg
	(*APIRequest_DiscoverGamesMsg)(nil),      // 7: api.APIRequest.DiscoverGamesMsg
	(*APIRequest_JoinGameMsg)(nil),           // 8: api.APIRequest.JoinGameMsg
	(*APIRequest_SteerSnakeMsg)(nil),         // 9: api.APIRequest.SteerSnakeMsg
	(*APIRequest_GetGameStateMsg)(nil),       // 10: api.APIRequest.GetGameStateMsg
	(*APIRequest_ExitGameMsg)(nil),           // 11: api.APIRequest.ExitGameMsg
	(*APIRequest_DisconnectMsg)(nil),         // 12: api.APIRequest.DisconnectMsg
	(*APIResponse_SuccessConnectMsg)(nil),    // 13: api.APIResponse.SuccessConnectMsg
	(*APIResponse_AckMsg)(nil),               // 14: api.APIResponse.AckMsg
	(*APIResponse_ErrorMsg)(nil),             // 15: api.APIResponse.ErrorMsg
	(*APIResponse_GameListMsg)(nil),          // 16: api.APIResponse.GameListMsg
	(*APIResponse_GameStateMsg)(nil),         // 17: api.APIResponse.GameStateMsg
	(*APIResponse_GameListMsg_GameInfo)(nil), // 18: api.APIResponse.GameListMsg.GameInfo
	(*APIResponse_GameStateMsg_Coord)(nil),   // 19: api.APIResponse.GameStateMsg.Coord
	(*APIResponse_GameStateMsg_Snake)(nil),   // 20: api.APIResponse.GameStateMsg.Snake
	(*APIResponse_GameStateMsg_Player)(nil),  // 21: api.APIResponse.GameStateMsg.Player
}
var file_api_proto_depIdxs = []int32{
	4,  // 0: api.APIRequest.connect:type_name -> api.APIRequest.ConnectMsg
	5,  // 1: api.APIRequest.ping:type_name -> api.APIRequest.PingMsg
	6,  // 2: api.APIRequest.create_game:type_name -> api.APIRequest.CreateGameMsg
	7,  // 3: api.APIRequest.discover_games:type_name -> api.APIRequest.DiscoverGamesMsg
	8,  // 4: api.APIRequest.join_game:type_name -> api.APIRequest.JoinGameMsg
	9,  // 5: api.APIRequest.steer_snake:type_name -> api.APIRequest.SteerSnakeMsg
	10, // 6: api.APIRequest.get_game_state:type_name -> api.APIRequest.GetGameStateMsg
	11, // 7: api.APIRequest.exit_game:type_name -> api.APIRequest.ExitGameMsg
	12, // 8: api.APIRequest.disconnect:type_name -> api.APIRequest.DisconnectMsg
	13, // 9: api.APIResponse.successConnect:type_name -> api.APIResponse.SuccessConnectMsg
	14, // 10: api.APIResponse.ack:type_name -> api.APIResponse.AckMsg
	15, // 11: api.APIResponse.error:type_name -> api.APIResponse.ErrorMsg
	16, // 12: api.APIResponse.game_list:type_name -> api.APIResponse.GameListMsg
	17, // 13: api.APIResponse.game_state:type_name -> api.APIResponse.GameStateMsg
	0,  // 14: api.APIRequest.SteerSnakeMsg.direction:type_name -> api.Direction
	18, // 15: api.APIResponse.GameListMsg.games:type_name -> api.APIResponse.GameListMsg.GameInfo
	20, // 16: api.APIResponse.GameStateMsg.snakes:type_name -> api.APIResponse.GameStateMsg.Snake
	19, // 17: api.APIResponse.GameStateMsg.foods:type_name -> api.APIResponse.GameStateMsg.Coord
	21, // 18: api.APIResponse.GameStateMsg.players:type_name -> api.APIResponse.GameStateMsg.Player
	19, // 19: api.APIResponse.GameStateMsg.Snake.points:type_name -> api.APIResponse.GameStateMsg.Coord
	0,  // 20: api.APIResponse.GameStateMsg.Snake.head_direction:type_name -> api.Direction
	1,  // 21: api.APIResponse.GameStateMsg.Player.role:type_name -> api.APIResponse.GameStateMsg.Role
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIRequest_ConnectMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIRequest_PingMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIRequest_CreateGameMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIRequest_DiscoverGamesMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIRequest_JoinGameMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIRequest_SteerSnakeMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIRequest_GetGameStateMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIRequest_ExitGameMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIRequest_DisconnectMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIResponse_SuccessConnectMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIResponse_AckMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIResponse_ErrorMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIResponse_GameListMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIResponse_GameStateMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIResponse_GameListMsg_GameInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIResponse_GameStateMsg_Coord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIResponse_GameStateMsg_Snake); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIResponse_GameStateMsg_Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*APIRequest_Connect)(nil),
		(*APIRequest_Ping)(nil),
		(*APIRequest_CreateGame)(nil),
		(*APIRequest_DiscoverGames)(nil),
		(*APIRequest_JoinGame)(nil),
		(*APIRequest_SteerSnake)(nil),
		(*APIRequest_GetGameState)(nil),
		(*APIRequest_ExitGame)(nil),
		(*APIRequest_Disconnect)(nil),
	}
	file_api_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*APIResponse_SuccessConnect)(nil),
		(*APIResponse_Ack)(nil),
		(*APIResponse_Error)(nil),
		(*APIResponse_GameList)(nil),
		(*APIResponse_GameState)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		EnumInfos:         file_api_proto_enumTypes,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_rawDesc = nil
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
